// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz9Vzmz-K5Emjld8TP-5Y3_dLLL-E2ovM',
    appId: '1:268901918998:web:29dd6489687ebc38098837',
    messagingSenderId: '268901918998',
    projectId: 'nubmed-1ab30',
    authDomain: 'nubmed-1ab30.firebaseapp.com',
    storageBucket: 'nubmed-1ab30.firebasestorage.app',
    measurementId: 'G-MTX9N5XJDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAulrpNhV2K0EosKF_9SN3RloxkjzO8yBM',
    appId: '1:268901918998:android:565a74fc55b180f5098837',
    messagingSenderId: '268901918998',
    projectId: 'nubmed-1ab30',
    storageBucket: 'nubmed-1ab30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASStBihHTOi-BL5sFRY6GZiQiIUpndVLA',
    appId: '1:268901918998:ios:34258dc7d8216a15098837',
    messagingSenderId: '268901918998',
    projectId: 'nubmed-1ab30',
    storageBucket: 'nubmed-1ab30.firebasestorage.app',
    iosBundleId: 'com.example.nubmed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASStBihHTOi-BL5sFRY6GZiQiIUpndVLA',
    appId: '1:268901918998:ios:34258dc7d8216a15098837',
    messagingSenderId: '268901918998',
    projectId: 'nubmed-1ab30',
    storageBucket: 'nubmed-1ab30.firebasestorage.app',
    iosBundleId: 'com.example.nubmed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz9Vzmz-K5Emjld8TP-5Y3_dLLL-E2ovM',
    appId: '1:268901918998:web:0d6620ce9923446a098837',
    messagingSenderId: '268901918998',
    projectId: 'nubmed-1ab30',
    authDomain: 'nubmed-1ab30.firebaseapp.com',
    storageBucket: 'nubmed-1ab30.firebasestorage.app',
    measurementId: 'G-CK73GZVV36',
  );
}
